config/routes.rb
Rails.application.routes.draw do
  get 'squad_places/edit'
  devise_for :users
  root to: 'squads#index'
  resources :squads do
    resources :players, only: [:new, :create, :edit, :update]
    resources :squad_rows, only: [:new, :create, :edit, :update]
  end
  resources :players, only: [:destroy]
  resources :squad_places, only: [:edit, :update, :destroy] do
  end
end

app/models/squad_place.rb
# == Schema Information
#
# Table name: squad_places
#
#  id           :bigint(8)        not null, primary key
#  name         :string
#  number       :integer
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  squad_row_id :bigint(8)
#

class SquadPlace < ApplicationRecord
  belongs_to :squad_row
  has_many :players, dependent: :destroy

  def self.autocreate(position_names, squad)
    position_names.each_with_index do |position_name, index|
      SquadPlace.create(name: position_name, number: index + 1, squad: squad)
    end
  end
end

app/controllers/squad_places_controller.rb
class SquadPlacesController < ApplicationController

  def edit
    @squad_place = SquadPlace.find(params[:id])
  end

  def update
    @squad_place = SquadPlace.find(params[:id])
    if @squad_place.update(squad_place_params)
      redirect_to squad_path(@squad_place.squad_row.squad)
    else
      render :edit
    end
  end

  def destroy
    @squad_place = SquadPlace.find(params[:id])
    if @squad_place.players.empty?
      @squad_place.destroy
      redirect_to squad_path(@squad_place.squad_row.squad)
    end
  end

  private

  def squad_place_params
    params.require(:squad_place).permit(:name, :squad_row_id)
  end
end

app/views/squad_places/_form.html.erb
<%= simple_form_for @squad_place do |f| %>
  <%= f.input :name %>
  <%= f.association :squad_row  %>
  <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/squad_places/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <h1>Update Squad Place</h1>
      <%= render 'form' %>
      <div style="margin-top: 20px"></div>
      <%= link_to squad_place_path(@squad_place), method: :delete do %>
        <i class="fas fa-trash-alt"></i> Remove
      <% end %>
    </div>
  </div>
</div>