config/routes.rb
Rails.application.routes.draw do
  get 'squad_places/edit'
  devise_for :users
  root to: 'squads#index'
  resources :squads do
    resources :players, only: [:new, :create, :edit, :update]
    resources :squad_rows, only: [:new, :create, :edit, :update]
  end
  resources :players, only: [:destroy]
  resources :squad_places, only: [:edit, :update, :destroy] do
  end
end

app/models/player.rb
# == Schema Information
#
# Table name: players
#
#  id             :bigint(8)        not null, primary key
#  first_name     :string
#  last_name      :string
#  nation         :string
#  age            :integer
#  potential_high :integer
#  potential_low  :integer
#  rating         :integer
#  badge          :string
#  status         :integer
#  photo          :string
#  squad_place_id :bigint(8)
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#

class Player < ApplicationRecord
  belongs_to :squad_place
  belongs_to :avatar
  acts_as_taggable_on :positions
  enum status: [:squad, :loan, :youth]
  after_create :give_order_number

  POSITIONS = %w(GK LB CB RB DM LM CM RM CAM LW CF ST RW)
  BADGES = ["futbol", "seedling", "star", "crown", "heart", "gem", "trash", "lemon", "shield-alt"]
  FACES = %w(face_1 face_2 face_3 face_4 face_5 face_6 face_7)

  def full_name
    "#{first_name} #{last_name}"
  end

  def last_initial
    "#{first_name[0]}. #{last_name}"
  end

  def give_order_number
    return if order

    self.order = squad_place.players.count
    save
  end

  def squad
    squad_place.squad_row.squad
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController

  def new
    @squad = Squad.find(params[:squad_id])
    @player = Player.new
  end

  def create
    @squad = Squad.find(params[:squad_id])
    @player = Player.new(player_params)
    if @player.save
      redirect_to squad_path(@squad)
    else
      render :new
    end
  end

  def edit
    @player = Player.find(params[:id])
    @squad = @player.squad_place.squad_row.squad
  end

  def update
    @player = Player.find(params[:id])
    @player.update(player_params)
    respond_to do |format|
      format.html { redirect_to squad_path(@player.squad_place.squad_row.squad) }
      format.js
    end
  end

  def destroy
    @player = Player.find(params[:id])
    @player.destroy
    redirect_to squad_path(@player.squad)
  end

  private

  def player_params
    params.require(:player).permit(:first_name, :last_name, :nation, :age, :potential_low, :potential_high, :rating, :badge, :avatar_id, :status, :squad_place_id, position_list: [])
  end
end

app/views/players/_card.html.erb
<div id="player-<%= player.id %>" class="squad-player-card" draggable="true"  data-action="dragstart->squadplace#playerDragHandler">
  <div class="player-card-avatar">
    <% if player.avatar.blank? %>
      <%= image_tag "avatar_1.png" %>
    <% else %>
      <%= image_tag player.avatar.photo %>
    <% end %>
  </div>
  <div class="player-card-info">
    <div class="player-card-first">
      <p><%= player.first_name %></p>
    </div>
    <div class="player-card-name">
      <p><%= player.last_name %></p>
    </div>
  </div>
  <div class="player-card-rating">
    <p><%= player.rating %></p>
    <div class="squad-player-form">
      <%= simple_form_for [@squad, player] do |f| %>
        <% f.input :squad_place_id, as: :hidden %>
      <% end %>
    </div>
  </div>
</div>

app/views/players/_form.html.erb
<%= simple_form_for [@squad, @player] do |f| %>
  <div style="display:flex;justify-content: space-between;">
    <%= f.input :first_name %>
    <%= f.input :last_name %>
    <%= f.input :nation %>
  </div>
  <div style="display:flex;justify-content: space-between;">
    <%= f.input :age %>
    <%= f.input :rating %>
    <%= f.input :potential_low %>
    <%= f.input :potential_high %>
  </div>
  <div style="display:flex;justify-content: space-between;">
    <div class="badge-legend">
      <small><i class="fas fa-crown"></i> Prem&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;| 94-95</small><br>
      <small><i class="fas fa-star"></i> Champ&nbsp;&nbsp;&nbsp;&nbsp;| 90-93</small><br>
      <small><i class="fas fa-gem"></i> Lg1&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;| 88-89</small><br>
      <small><i class="fas fa-shield-alt"></i> Lg2&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;| 85-87</small><br>
      <small><i class="fas fa-futbol"></i> VN&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;| 80-84</small><br>
      <small><i class="fas fa-seedling"></i> Seedling&nbsp;| Youth</small>
    </div>
    <%= f.input :badge, collection: Player::BADGES %>
    <%= f.input :status, collection: Player.statuses.keys %>
    <%= f.association :squad_place, collection: @squad.squad_places  %>
  </div>
  <%= f.input :position_list, as: :check_boxes, collection: Player::POSITIONS %>
  <div style="display:flex;flex-wrap: wrap;">
    <% Avatar.find_each do |avatar| %>
      <div style="display:flex;flex-direction:column;">
        <%= image_tag avatar.photo, style: "margin-right: 5px;width: 100px;
      height: 100px;" %>
        <span><%= avatar.photo %></span>
      </div>
    <% end %>
  </div>
  <%= f.association :avatar %>
  <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/players/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-10 col-sm-offset-1" style="margin-bottom: 50px">
      <div style="display: flex;justify-content: space-between;align-items: baseline;">
        <div style="display: flex">
          <%= image_tag @player.avatar.photo, class: "navbar-wagon avatar", style: "background-color: transparent; box-shadow:none; margin-top:10px;" %>
          <h1>
            <%= @player.first_name %> <%= @player.last_name %>
          </h1>
        </div>
        <%= link_to player_path(@player), method: :delete,
          data: { confirm: "Remove player from squad?" } do %>
          <i class="fas fa-trash"></i>
        <% end %>
      </div>
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/players/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-10 col-sm-offset-1" style="margin-bottom: 50px">
      <h1>Add Player</h1>
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/players/update.js.erb
function refreshForm(innerHTML) {
  const newReviewForm = document.getElementById('new_review');
  newReviewForm.innerHTML = innerHTML;
}

function addPlayer(reviewHTML) {
  const squadPlaces = document.getElementById('squad-place-card-<%= player.squad_place.id %>');
  squadPlaces.innerHTML = reviewHTML;
}

<% if @player.errors.any? %>
  // refreshForm('<%= j render "reviews/form", restaurant: @restaurant, review: @review %>');
<% else %>
  addPlayer('<%= j render "squad_places/index" %>');
  // refreshForm('<%= j render "reviews/form", restaurant: @restaurant, review: Review.new %>');
<% end %>