config/routes.rb
Rails.application.routes.draw do
  get 'squad_places/edit'
  devise_for :users
  root to: 'squads#index'
  resources :squads do
    resources :players, only: [:new, :create, :edit, :update]
    resources :squad_rows, only: [:new, :create, :edit, :update]
  end
  resources :players, only: [:destroy]
  resources :squad_places, only: [:edit, :update, :destroy] do
  end
end

app/models/squad.rb
# == Schema Information
#
# Table name: squads
#
#  id           :bigint(8)        not null, primary key
#  user_id      :bigint(8)
#  formation_id :bigint(8)
#  name         :string
#  badge        :string
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Squad < ApplicationRecord
  belongs_to :user
  belongs_to :formation
  has_many :squad_rows, dependent: :destroy
  has_many :squad_places, through: :squad_rows
  has_many :players, through: :squad_places
  after_create :build_squad_rows

  def build_squad_rows
    return if squad_rows.count >= 4
    (1..4).to_a.each do |number|
      SquadRow.create(
        number: number.to_i,
        squad: self
      )
    end
  end

  def players_except_youth
    players.where.not(status: "youth")
  end

  def first_row_players
    squad_rows.find_by(number: 1).players
  end

  def second_row_players
    squad_rows.find_by(number: 2).players
  end

  def third_row_players
    squad_rows.find_by(number: 3).players
  end

  def fourth_row_players
    squad_rows.find_by(number: 4).players
  end
end

app/controllers/squads_controller.rb
class SquadsController < ApplicationController
  def index
    @squads = current_user.squads
  end

  def show
    @squad = Squad.find(params[:id])
  end

  def new
    @squad = Squad.new
  end

  def create
    @squad = Squad.new(squad_params)
    @squad.user = current_user
    if @squad.save
      redirect_to squad_path(@squad)
    else
      render :new
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private

  def squad_params
    params.require(:squad).permit(:name, :formation_id)
  end
end

app/helpers/squad_helper.rb
module SquadHelper

  def position_class(position)
    if %w(LW CF ST RW).include?(position)
      'fw'
    elsif %w(DM LM CM RM CAM).include?(position)
      'mf'
    elsif %w(LB CB RB).include?(position)
      'df'
    elsif 'GK' == position
      'gk'
    end
  end
end

app/views/squads/_form.html.erb
<%= simple_form_for @squad do |f| %>
  <%= f.input :name %>
  <%= f.association :formation %>
  <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/squads/_header.html.erb
<div class="squad-header"> <!-- flex -->
  <div class="squad-header-name">
    <h5><%= @squad.name %></h5>
  </div>
  <div class="squad-header-titles">
    <div class="squad-header-labels" style="background-color: #20B6D9">
      <p style="color:#20B6D9">Squad</p>
    </div>
    <div class="squad-header-title">
      <h5>All ( <%= @squad.players_except_youth.count %> / 52 )</h5>
    </div>
    <div class="squad-header-title">
      <h5>FW ( <%= @squad.first_row_players.count %> )</h5>
    </div>
    <div class="squad-header-title">
      <h5>MF ( <%= @squad.second_row_players.count %> )</h5>
    </div>
    <div class="squad-header-title">
      <h5>DF ( <%= @squad.third_row_players.count %> )</h5>
    </div>
    <div class="squad-header-title">
      <h5>GK ( <%= @squad.fourth_row_players.count %> )</h5>
    </div>
  </div>
  <div class="squad-header-stats">
    <div class="squad-header-labels">
      <p style="border-top: 1px solid #707070;">&nbsp;</p>
      <p>Squad</p>
      <p>Loan</p>
      <p>Youth</p>
    </div>
    <% columns = [@squad.players, @squad.first_row_players, @squad.second_row_players, @squad.third_row_players, @squad.fourth_row_players] %>
    <% columns.each do |players| %>
      <div class="squad-header-stat">
        <div class="squad-header-stat-row" style="border-bottom: 1px solid #DBDBDB;background-color: #707070;color: #DBDBDB;">
          <div class="squad-header-stat-row-one">
            <p><i class="fas fa-users"></i></p>
          </div>
          <div class="squad-header-stat-row-two">
            <p><i class="fas fa-star"></i></p>
          </div>
        </div>
        <div class="squad-header-stat-row">
          <div class="squad-header-stat-row-one">
            <p><%= all = players.where(status: "squad").count %></p>
          </div>
          <div class="squad-header-stat-row-two">
            <p><%= all > 0 ? (players.where(status: "squad").pluck(:rating).inject(:+) / all.to_f).round(2) : "-" %></p>
          </div>
        </div>
        <div class="squad-header-stat-row">
          <div class="squad-header-stat-row-one">
            <p><%= loan = players.where(status: "loan").count %></p>
          </div>
          <div class="squad-header-stat-row-two">
            <p><%= loan > 0 ? (players.where(status: "loan").pluck(:rating).inject(:+) / loan.to_f).round(2) : "-" %></p>
          </div>
        </div>
        <div class="squad-header-stat-row">
          <div class="squad-header-stat-row-one">
            <p><%= youth = players.where(status: "youth").count %></p>
          </div>
          <div class="squad-header-stat-row-two">
             <p><%= youth > 0 ? (players.where(status: "youth").pluck(:rating).inject(:+) / youth.to_f).round(2) : "-" %></p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/squads/_squad_body.html.erb
<%= render 'squads/header' %>

<% @squad.squad_rows.order(number: :asc).each do |row| %>
  <div class="squad-row" id="squad-row-<%= row.id %>">
    <% row.squad_places.each do |place| %>
      <div class="squad-place-card" id="squad-place-card-<%= place.id %>" data-controller="squadplace">
        <div class="squad-place-name">
          <h5><%= link_to place.name, edit_squad_place_path(place) %></h5>
          <span class="squad-place-count"><%= place.players.count %></span>
        </div>
        <div class="squad-place-player" id="squad-place-players-<%= place.id %>" data-action="drop->squadplace#playerDropHandler dragover->squadplace#playerDragOverHandler dragleave->squadplace#playerDragExitHandler" data-id="<%= place.id %>">
          <% Player.statuses.keys.each do |status| %>
            <% if place.players.where(status: status).any? %>
              <div class="<%= status %>-status">
                <% place.players.where(status: status).order(rating: :desc).each do |player| %>
                  <%= render partial: 'players/card', locals: { player: player } %>
                <% end %>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
    <% end %>
    <div class="row-actions">
      <%= link_to edit_squad_squad_row_path(@squad, row) do %>
        <i class="far fa-edit"></i>
      <% end %>
    </div>
  </div>
<% end %>

<!-- Links to row actions -->
<div class="squad-row" id="squad-row-new">
  <div class="row-actions">
    <%= link_to new_squad_squad_row_path(@squad) do %>
      <i class="fas fa-plus-square"></i>
    <% end %>
  </div>
</div>

app/views/squads/_squad_list.html.erb
<div class="squad-list-row-header">
  <div class="squad-player-info">
    <div class="squad-player-basic">
      <p>Player (<%= @squad.players.where.not(status: "youth").count %>)</p>
      <div class="squad-player-name" style="margin-left:10px;font-weight: bold;">
        <%= link_to new_squad_player_path(@squad), class: "color-orange" do %>
          <i class="fas fa-plus color-red"></i>
        <% end %>
      </div>
    </div>
  </div>
  <div class="squad-player-stats-header">
    <div class="squad-player-age" style="margin-left: 3px;">
      <p>A</p>
    </div>
    <div class="squad-player-rating" style="margin-left: 3px;">
      <p>R</p>
    </div>
    <div class="squad-player-potential" style="min-width: 50px;text-align: center;">
      <p>P</p>
    </div>
  </div>
</div>
<% @squad.squad_rows.each do |squad_row| %>
  <div class="squad-list-row-wrapper">
    <% squad_row.players.order(rating: :desc).each do |player| %>
      <div class="squad-list-row">
        <div class="squad-player-info">
          <div class="squad-player-basic">
            <div class="squad-player-badge">
              <i class="fas fa-<%= player.badge %>"></i>
            </div>
            <div class="squad-player-name">
              <p><%= link_to player.full_name, edit_squad_player_path(@squad, player) %></p>
            </div>
          </div>
          <div class="squad-player-positions">
            <% player.position_list.each do |position| %>
              <span class="<%= position_class(position) %>"><%= position %></span>
            <% end %>
          </div>
        </div>
        <div class="squad-player-stats">
          <div class="squad-player-age">
            <p><%= player.age %></p>
          </div>
          <div class="squad-player-rating">
            <p><%= player.rating %></p>
          </div>
          <div class="squad-player-potential">
            <p><%= "#{player.potential_low} - #{player.potential_high}" %></p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/squads/edit.html.erb
<h1>Squads#edit</h1>
<p>Find me in app/views/squads/edit.html.erb</p>

app/views/squads/index.html.erb
<div class="squad-index-header">
  <h1>Squads</h1>
  <%= link_to new_squad_path do %>
    <i class="fas fa-plus"></i>
  <% end %>
</div>
<% @squads.each do |squad| %>
  <p><%= link_to squad.name, squad_path(squad)%></p>
<% end %>

app/views/squads/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <h1>New Squad</h1>

      <%= render 'form' %>
    </div>
  </div>

</div>

app/views/squads/show.html.erb
<div class="squad-container">
  <div class="squad-list" id="squad-list">
    <%= render partial: 'squads/squad_list' %>
  </div>
  <div class="squad-body" id="squad-body">
    <%= render partial: 'squads/squad_body' %>
  </div>
</div>